ingress:
  host: "minio-test2.fairtracks.sigma2.no"
resources:
  requests:
    cpu: "2"
    memory: 2G
  limits:
    cpu: "4"
    memory: 2G
persistentStorage:
  existingClaim: "8fbdd1bd-31a5-4ffd-a5b0-eaf10e519732"
  existingClaimName: "fairtracks-ns10022k"
  subPath: "/"
  readOnly: false
uid: 240795
gid: 205709
username: minio
supplementalGroups:
  - name: ""
    gid: ""
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
  aai:
    client_id: provided-by-toolkit
    client_secret: provided-by-toolkit
    issuer_url: https://apps-auth.sigma2.no/
    scopes:
      - openid
      - profile
      - email
    authorized_principals: []
    owner: provided-by-toolkit
    userinfo_url: provided-by-tookit
    token_url: provided-by-toolkit
    auth_url: provided-by-toolkit
advanced:
  accessKey: "accesskeyexample"
  secretKey: "Pzr9YPNe*daAan"
  dockerImage: quay.io/uninett/minio:20210915-90f987b
